baseURL = "https://todarch.github.io/"
languageCode = "en-us"
title = "Todarch"
theme = "hyde"

[params]
  themeColor = "theme-base-0d"
  description = "Technical blog on experience, learning, problem-solving while building Todarch application."
